name: certbot-dns-porkbun
summary: Porkbun DNS Authenticator plugin for Certbot
description: Porkbun DNS Authenticator plugin for Certbot
confinement: strict
grade: stable
base: core20
adopt-info: certbot-dns-porkbun
architectures:
  - build-on: amd64
  - build-on: arm64
  - build-on: armhf

parts:
  certbot-dns-porkbun:
    plugin: python
    source: .
    override-pull: |
      snapcraftctl pull
      snapcraftctl set-version `grep ^__version__ $SNAPCRAFT_PART_SRC/certbot_dns_porkbun/__init__.py | cut -f2 -d= | tr -d "\"[:space:]\""`
    build-environment:
      - PIP_CONSTRAINT: $SNAPCRAFT_PART_SRC/snap-constraints.txt
      - SNAP_BUILD: "True"
    requirements:
      - snap-requirements.txt
    build-packages:
      - gcc
      - git
      - build-essential
      - libssl-dev
      - libffi-dev
      - python3-dev
      - cargo
  certbot-metadata:
    plugin: dump
    source: .
    stage: [ setup.py, certbot-shared ]
    override-pull: |
      snapcraftctl pull
      mkdir -p $SNAPCRAFT_PART_SRC/certbot-shared

slots:
  certbot:
    interface: content
    content: certbot-1
    read:
      - $SNAP/lib/python3.8/site-packages

plugs:
  certbot-metadata:
    interface: content
    content: metadata-1
    target: $SNAP/certbot-shared
